sudo: required

language: python

services:
  - docker

before_install:
  - docker --version

script:
  - docker build -t alkemic/webrss .

after_success:
  - |
    if [ "$TRAVIS_TAG" != "" ] || [ "$TRAVIS_BRANCH" == "master" ]
    then
      docker login -u=alkemic -p="${PASSWORD}"
      docker push alkemic/webrss
      if [ "$TRAVIS_TAG" != "" ] && [[ $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]
      then
        revs=( ${TRAVIS_TAG//./ } )
        docker push alkemic/webrss:${revs[0]}.${revs[1]}.${revs[2]}
        docker push alkemic/webrss:${revs[0]}.${revs[1]}
        docker push alkemic/webrss:${revs[0]}
      fi
    fi

env:
  global:
    secure: "B/TR3GZHkE2ZcPT3XuFoQ0ERERO3uKRn0J6+or7BJz1vP6KVS62xiHXM89JG+u2QBTaiBu0ZOE4QaNqG4KzwIPB7E6ToXrx3+n926gs/s7BoLB4n1JjRSFIMqPHaf2NjWustJj6TqtThE2zGXbi8gcEfnecEr9/X1IODQ/aJAT4="
