version: '3'

services:
  app:
    image: alkemic/webrss
    restart: always
    network_mode: "bridge"
    links:
      - db
    environment:
      - DB_DSN=root:@tcp(127.0.0.1:13306)/webrss?parseTime=true
      - BIND_ADDR=:8080
      - PER_PAGE=75
    ports:
      - 8080:8080

  db:
    image: mysql:5.6
    network_mode: "bridge"
    restart: always
    volumes:
      - ./mysql_data/:/var/lib/mysql/
    environment:
      - MYSQL_DATABASE=webrss
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes # of course you should use some password
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
